### ISSUE TITLE
Lack of battery_level makes the module fail

### ISSUE THREAD

**Issue by EmmanuelLM** [ludeeus/pytraccar#1]
Hello, could you please add a default for battery_level as this is not consistently reported, which makes the module fail to load.
I am using http://demo5.traccar.org and here is what is reported:

http://demo5.traccar.org/api/positions:
[{"id":302901598,"attributes":{"sat":9,"distance":6.13,"totalDistance":9273721.8,"motion":false},"deviceId":8145,"type":null,"protocol":"gt06","serverTime":"2018-12-14T16:42:32.537+0000","deviceTime":"2018-12-14T16:42:30.000+0000","fixTime":"2018-12-14T16:42:30.000+0000","outdated":false,"valid":true,"latitude":51.46371666666667,"longitude":-0.09139666666666667,"altitude":0.0,"speed":0.0,"course":0.0,"address":null,"accuracy":0.0,"network":{"radioType":"gsm","considerIp":false,"cellTowers":[{"cellId":10915,"locationAreaCode":21105,"mobileCountryCode":234,"mobileNetworkCode":10}]}}]

http://demo5.traccar.org/api/devices
[{"id":8145,"attributes":{},"groupId":0,"name":"piaggio mp3","uniqueId":"352887075140123","status":"online","lastUpdate":"2018-12-14T16:43:49.084+0000","positionId":302902611,"geofenceIds":[],"phone":"07542085783","model":"","contact":"","category":"bicycle","disabled":false}]

http://demo5.traccar.org/api/geofences
[]

**Comment by EmmanuelLM** [comment]
I have a gsm tracker on my motorbike and have linked it to the demo site of
traccar.org (protocol GT06).
Not doing anything special aside from that.

**Comment by ludeeus** [comment]
that is fine (i guess), but how are you using this python package?

**Comment by EmmanuelLM** [comment]
Oh, I see, using it in home-assistant with the new module

**Comment by ludeeus** [comment]
I see :)
if you have an issue with a platform in Home Assistant you should use the issue tracker for that project :)
<https://github.com/home-assistant/home-assistant/issues> to report issues with it.
