### ISSUE TITLE
Error combining data from Traccar when device enters geofence area

### ISSUE THREAD

**Issue by tomhash2** [ludeeus/pytraccar#5]
Hello,

I'm using Traccar API through Home Assistant and I'm seeing strange behavior.

When my device is in geofenced area that is associated with it I have "Error combining data from Traccar" in logs.

I have one device: Android client.
I'm using Traccar 4.3 and HA 0.91.2.

Thank you.

**Comment by ludeeus** [comment]
Please provide the API output from traccar you get by running this client with debug logging

**Comment by tomhash2** [comment]
Forgive me but my python skills are near zero. How can I enable debug mode in code? I managed to get self._device_info displayed in logs:

"2019-04-10 21:23:59 ERROR (MainThread) [pytraccar.api] Error combining data from Traccar, {'195313': 
{'traccar_id': 1, 'device_id': 'tomi_traccar', 'address': None, 'updated': '2019-04-10T19:14:59.347+0000', 'category': 'person', 'latitude': 50.1503576, 'longitude': 18.8571883, 'altitude': 339.0, 'course': 0.0, 'speed': 0.0, 'battery': 30.0, 'motion': False, 'geofence': None}}\n"

It looks like the problem is that geofence is None witch means that geofence = self.geofences[dev['geofenceIds'][0]] does not work. It is hard to me to debug further...

Can you help?

**Comment by tomhash2** [comment]
I have some more info... It turned out that my traccar /api/geofences returns no data. Now I am investigating this. Sorry for bothering you.

**Comment by ludeeus** [comment]
Create a python file with this content and run it:
```python
import asyncio
import aiohttp
from api import API


async def test():
    """Debug of pytraccar."""
    async with aiohttp.ClientSession() as session:
        host = input("IP: ")
        username = input("Username: ")
        password = input("Password: ")
        print("\n\n\n")
        data = API(LOOP, session, username, password, host)
        await data .test_connection()
        print("Authenticated:", data.authenticated)
        if data.authenticated:
            await data.get_device_info()
            print("Authentication:", data.authenticated)
            print("Geofences:", data.geofences)
            print("Devices:", data.devices)
            print("Positions:", data.positions)
            print("Device info:", data.device_info)

LOOP = asyncio.get_event_loop()
LOOP.run_until_complete(test())
```

Or use the logger component in homeassistant https://www.home-assistant.io/components/logger/

**Comment by tomhash2** [comment]
Eventually it turned out that this problem was not related to pytraccar. I have used separate login in traccar (which is not admin) for HA to read data. I forgot to share geofence info with this user but shared device info. In the end there was value in dev['geofenceIds'] but self._geofences was empty. That's it :)
