### ISSUE TITLE
Help on using the pytraccar

### ISSUE THREAD

**Issue by batalhadematos** [ludeeus/pytraccar#8]
Hello,
I am new to python and using Traccar for a while.
I found your pytraccar api and it is great.

Can you please send me some samples of how can I pass paratemeters/attributes to the API?
I basically need 2 things:
- Get a specific device information by uniqueId;
- Get information about the last device position;

By using the example.py I can get the desired information but always show information for only one device.
I need to know how can I pass attributes/parameters in order to get the same information for a single device by using 'uniqueId'

Thank you very much and congratulations for the great efforts for building this API.

Best reards

**Comment by ludeeus** [comment]
Hi,

It is so long since I worked on this, so I have no clue if that is even possible.
But by looking at the code something like this might work.

```python
await data.get_device_info()
device = [x for x in traccar.devices if x["uniqueId"] == "111111111"].pop()
position = [x for x in traccar.positions if x["id"] == device["positionId"]].pop()
print(device)
print(position)
```
